<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChamberControlSimulator.Core\ChamberControlSimulator.Core.csproj" />
    <ProjectReference Include="..\ChamberControlSimulator.Plc.Abstractions\ChamberControlSimulator.Plc.Abstractions.csproj" />
  </ItemGroup>

</Project>
